### ISSUE TITLE
you can change react to any cryptographic logo bruh will suits good!..

### ISSUE THREAD

**Issue by hakxcore** [dewanshchaudhari/crypto-dashboard#1]
https://github.com/dewanshchaudhari/crypto-dashboard/blob/8d084c3024a68131605eda1423b1f7adfe762166/public/index.html#L12

**Comment by dewanshchaudhari** [comment]
Yes, but this design was a part of a challenge and the mockups were already provided.
If you have any ideas regarding this feel free to open a PR
